import {  Poppins } from "next/font/google";
import "./globals.css";
import { NextUiProvider } from "@/providers/next-ui-provider";
import NavbarComponent from "@/components/navbar";
import FooterComponent from "@/components/footer";

const poppins = Poppins({ 
  subsets: ["latin"],
  weight : ['100', '200' , '300' , '400', '500' , '600' , '700' , '800' , '900']
 });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NextUiProvider>
          <NavbarComponent/>
            {children}
          <FooterComponent/>
        </NextUiProvider>
      </body>
    </html>
  );
}
